### ISSUE TITLE
✨ Feat: 공용 라디오 버튼 컴포넌트

### ISSUE THREAD

**Issue by oceanlee-seoul** [codeit-2000/codeit-resources#7]
# 작업 설명

## 공용 라디오 버튼 컴포넌트

공용 사용할 커스텀 라디오 버튼을 개발합니다.

![Image](https://github.com/user-attachments/assets/550e10cd-3152-4adb-8cd2-73bf159bd875)

## 세부 작업 목록

- [ ] 커스텀 라디오 버튼 컴포넌트

**Comment by oris8** [comment]
가져가요
